name: Flutter Tests

on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.x

      - name: Get dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test

      - name: Run integration tests
        run: flutter drive --target=test_driver/app.dart
